// Read-only browser checks against an already-running workbench. Never submits GPU work.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.WORKBENCH_URL || 'http://127.0.0.1:8765';
(async () => {
  const browser = await chromium.launch({headless:true, channel:'msedge'});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await fs.mkdir('output/ui-v1.2', {recursive:true});
    await page.goto(base+'/objects');
    await page.locator('#kind option[value="multiview"]').waitFor({state:'attached'});
    await page.locator('#account-name').waitFor();
    assert.equal(await page.getByText('打开资产库',{exact:true}).count(), 0);
    const createTop = await page.locator('.page-header').evaluate(e=>e.getBoundingClientRect().top);
    await page.screenshot({path:'output/ui-v1.2/create.jpg',type:'jpeg',quality:80});
    await page.locator('[data-view="library"]').click();
    await page.locator('#library-panel').waitFor({state:'visible'});
    assert.equal(await page.locator('[data-view="library"]').evaluate(e=>e.classList.contains('active')),true);
    assert.equal(await page.locator('[data-view="create"]').evaluate(e=>e.classList.contains('active')),false);
    await page.mouse.move(1000,10);
    await page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished)));
    const settingsTop = await page.locator('.page-header').evaluate(e=>e.getBoundingClientRect().top);
    assert.equal(settingsTop, createTop);
    await page.screenshot({path:'output/ui-v1.2/settings.jpg',type:'jpeg',quality:80});
    await page.locator('[data-view="tasks"]').click();
    assert.equal(await page.locator('.page-header').evaluate(e=>e.getBoundingClientRect().top), createTop);
    await page.locator('.task-actions a[href^="/?task="]').first().click();
    await page.locator('.asset-card').first().waitFor();
    assert.match(await page.locator('#view-caption').innerText(),/当前任务/);
    await page.locator('[data-stage="source_frames"]').click();
    assert.match(await page.locator('#view-title').innerText(),/原始素材/);
    assert.equal(await page.locator('#image-output-count').isVisible(), false);
    await page.locator('.asset-media').first().click();
    await page.locator('#asset-dialog').waitFor({state:'visible'});
    const relations = await page.locator('[data-related-asset]').count();
    if(relations) await page.locator('[data-related-asset]').first().click();
    await page.keyboard.press('Escape');
    await page.locator('[data-stage="approved"]').click();
    await page.locator('.asset-select').first().check();
    await page.locator('#download-selected').waitFor({state:'visible'});
    await page.locator('.asset-card img').evaluateAll(images=>Promise.all(images.map(image=>image.decode())));
    await page.screenshot({path:'output/ui-v1.2/library-approved.jpg',type:'jpeg',quality:80});
    const downloadEvent = page.waitForEvent('download',{timeout:60000});
    await page.locator('#download-selected').click();
    const download = await downloadEvent;
    assert.match(download.suggestedFilename(),/模型.*\.zip$/);
    await download.saveAs(path.resolve('output/ui-v1.2/approved-models.zip'));
    await page.locator('#account-slot summary').click();
    assert.equal(await page.getByRole('link',{name:'切换账号'}).isVisible(),true);
    await page.locator('#account-slot summary').click();
    await page.setViewportSize({width:768,height:1000});
    await page.screenshot({path:'output/ui-v1.2/library-tablet.jpg',type:'jpeg',quality:80});
    const overflow = await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth);
    assert.equal(overflow,false,'Tablet layout must not overflow horizontally');
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({passed:true,headerTop:createTop,relations,errors,download:download.suggestedFilename()}));
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
